upstream drive_backend {
  server drive-backend:8000;
  keepalive 32;
}

server {
  listen       80;
  listen  [::]:80;
  server_name  localhost;

  gzip on;
  gzip_types text/plain text/css text/xml text/javascript application/javascript application/x-javascript;
  gzip_min_length 1024;
  gzip_vary on;

  root /usr/share/nginx/html;

  etag off;
  client_max_body_size 500M;

  include mime.types;
  types {
    # Manifest files
    application/manifest+json webmanifest;
  }

  # all assets contain hash in filename, cache forever
  location /assets/ {
    add_header Cache-Control "public, max-age=31536000, s-maxage=31536000, immutable";
    try_files $uri =404;
  }

  # all workbox scripts are compiled with hash in filename, cache forever
  location ^~ /workbox- {
    add_header Cache-Control "public, max-age=31536000, s-maxage=31536000, immutable";
    try_files $uri =404;
  }

  # image assets can be cached for a month
  location /images/ {
    add_header Cache-Control "public, max-age=2592000";
    try_files $uri =404;
  }

  # Proxy API endpoints to backend
  location ~ ^/(v1|v1.1|v1.4|v2|upload|storage)/ {
    proxy_pass http://drive_backend;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 300s;
    proxy_connect_timeout 75s;
  }

  # Proxy Athena WebSockets
  location ~ ^/ws {
    proxy_pass http://drive_backend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;
  }

  # assume that everything else is handled by the application router, by injecting the index.html
  location / {
    autoindex off;
    expires off;
    add_header Cache-Control "public, max-age=0, s-maxage=0, must-revalidate" always;

    try_files $uri /index.html =404;
  }

  location /404.html {
    internal;
  }

  location /50x.html {
    internal;
  }

  error_page  404              /404.html;
  error_page  500 502 503 504  /50x.html;
}
